name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-16.04]
        sqlserver-version: [2019, 2017]
        include:
          - os: windows-2019
            sqlserver-version: 2019
          - os: windows-2016
            sqlserver-version: 2019
    steps:
    - uses: ankane/setup-sqlserver@v1
      with:
        sqlserver-version: ${{ matrix.sqlserver-version }}
        accept-eula: true
    - run: sqlcmd -?
    - run: sqlcmd -U SA -P 'YourStrong!Passw0rd' -Q 'CREATE DATABASE testdb'
    - run: sqlcmd -U SA -P 'YourStrong!Passw0rd' -d testdb -Q 'SELECT @@VERSION'
