name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            sqlserver-version: 2022
          - os: ubuntu-20.04
            sqlserver-version: 2019
          - os: ubuntu-18.04
            sqlserver-version: 2019
          - os: ubuntu-18.04
            sqlserver-version: 2017
          - os: windows-2022
            sqlserver-version: 2022
          - os: windows-2022
            sqlserver-version: 2019
          - os: windows-2019
            sqlserver-version: 2019
    steps:
      - uses: actions/checkout@v3
      - uses: ./.
        with:
          sqlserver-version: ${{ matrix.sqlserver-version }}
          accept-eula: true
      - run: sqlcmd -?
      - run: sqlcmd -U SA -P 'YourStrong!Passw0rd' -Q 'CREATE DATABASE testdb'
      - run: sqlcmd -U SA -P 'YourStrong!Passw0rd' -d testdb -Q 'SELECT @@VERSION'
