name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04]
        # sqlserver-version: [2019, 2017]
        os: [ubuntu-18.04]
        sqlserver-version: [2019]
    steps:
    - uses: ankane/setup-sqlserver@v1
      with:
        sqlserver-version: ${{ matrix.sqlserver-version }}
    - run: sqlcmd -?
    - run: sqlcmd -Q 'CREATE DATABASE testdb'
    - run: sqlcmd -d testdb -Q 'SELECT @@VERSION'
